"use client";

import { motion } from "framer-motion";
import { BookOpen, ExternalLink } from "lucide-react";

const publications = [
  {
    title: "Exploring the natural pothole dataset generated by the abrasion and cavitation effects of river water on rocks",
    publisher: "Elsevier Inc",
    date: "Aug 24, 2024",
    description: "The Natural Pothole Dataset within River Environments is an extensive collection of 3992 high-resolution images documenting various natural potholes located in riverine settings. Each image has been rigorously annotated utilizing the YOLO object detection framework.",
    link: "https://www.sciencedirect.com/science/article/pii/S2352340924008370?via%3Dihub"
  },
  {
    title: "Coconut (Cocos nucifera) tree disease dataset: A dataset for disease detection and classification for machine learning applications",
    publisher: "Elsevier Inc",
    date: "Oct 15, 2023",
    description: "The dataset comprises 5,798 images across five disease categories. Intended for machine learning applications, facilitating disease detection and classification in coconut trees. This dataset supports advancements in plant pathology.",
    link: "https://www.sciencedirect.com/science/article/pii/S2352340923007692"
  }
];

export default function Publications() {
  return (
    <section id="publications" className="py-24 relative bg-black/20">
      <div className="container mx-auto px-6 md:px-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="mb-16"
        >
          <h2 className="text-3xl md:text-5xl font-display font-bold mb-4">
            Research & <span className="text-blue-400">Publications</span>
          </h2>
          <div className="w-20 h-1 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full"></div>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {publications.map((pub, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              className="glass-card rounded-2xl p-8 flex flex-col h-full group hover:-translate-y-2 transition-transform duration-300"
            >
              <div className="w-12 h-12 bg-blue-500/20 text-blue-400 rounded-xl flex items-center justify-center mb-6">
                <BookOpen size={24} />
              </div>
              
              <h3 className="text-xl font-bold text-white mb-2 leading-tight">{pub.title}</h3>
              <div className="flex items-center space-x-2 text-sm text-slate-400 mb-4 font-medium">
                <span className="text-blue-300">{pub.publisher}</span>
                <span>•</span>
                <span>{pub.date}</span>
              </div>
              
              <p className="text-slate-400 leading-relaxed mb-8 flex-grow">{pub.description}</p>
              
              <a
                href={pub.link}
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center space-x-2 text-sm font-bold text-white hover:text-blue-400 transition-colors mt-auto"
              >
                <span>Read Publication</span>
                <ExternalLink size={16} />
              </a>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
