import { PROFILE, EXPERIENCE, PROJECTS, RESEARCH, SKILL_GROUPS, ACHIEVEMENTS, CERTIFICATIONS } from "./data";

export const MASTER_KNOWLEDGE_BASE = JSON.stringify({ PROFILE, EXPERIENCE, PROJECTS, RESEARCH, SKILL_GROUPS, ACHIEVEMENTS, CERTIFICATIONS }, null, 2);
